### ISSUE TITLE
Error filtering the status in getOrderHistory

### ISSUE THREAD

**Issue by chancity** [kinecosystem/marketplace-server#170] opened 2018-09-05 14:58 UTC
If an external offer is created but never submitted getOrderHistory errors because it's populating the array with orders that are open...kin-devplatform-marketplace-server uses the same method of getting orders aswell.

https://github.com/kinecosystem/marketplace-server/blob/master/scripts/src/public/services/orders.ts#L337-L340

https://github.com/kinecosystem/kin-devplatform-marketplace-server/blob/master/scripts/src/public/services/orders.ts#L315-L318

**Comment by nitzantomer** [comment] 2018-09-05 16:40
I don't understand, what do you mean by "getOrderHistory errors"? 
Do you get an actual error or the result isn't what you'd expect?
In either case, please provide the response you get (error/result).

**Comment by nitzantomer** [comment] 2018-09-06 07:04
@chancity ^^

**Comment by chancity** [comment] 2018-09-06 07:59
Hey hey, so what happened was I created a pay_to_user offer and before submitting the offer id my program threw and exception causing it to crash.  I wasn't storing OrderIds at that time so the order was never submitted.  I thought hmm here's an endpoint to view offers and orders, maybe I can find my unsubmitted order id on one of those endpoints.  Nope wasn't in offers and orders is failing because and order had a status of "opened".

**Comment by chancity** [comment] 2018-09-06 08:03
Sorry I don't have the JSON error from the request but I have a pretty good idea what method in the marketplace server is throwing the exception.  Here: 
function orderDbToApi(order: db.Order, userId: string): Order {
	if (order.status === "opened") {
		throw OpenedOrdersUnreturnable();
	}

**Comment by nitzantomer** [comment] 2018-09-06 09:07
@chancity 
As I wrote in the other issue thread, opened orders are only used in the server and the client shouldn't care about them.
You are free to just create a new order for the same offer id, if the server finds an existing open order for that id then it will return the same one.  If it finds an order for that id with a status other than `pending` then you'll get an error.

What I still don't understand is how you received an error. To which endpoint did you call when you got it?

**Comment by chancity** [comment] 2018-09-06 12:50
SO on step 5 my program crashed, not related to the Market place API at all.  Upon restart I called step 6 and this is were the market place API threw an exception.  

When I get on my computer today I'll try to find the market place user id the exception is occurring on.

1. /users POST
2. /users/me/activate POST
3. Change trust operation 
4. /offers/external/orders POST
5. /orders/{order_id} POST //MY PROGRAM CRASHED
6. /orders GET //ERROR OCCURRED

**Comment by nitzantomer** [comment] 2018-09-06 14:08
@chancity 
Interesting.  It shouldn't return an error on step 6, just an empty array I guess.
Please provide us with the user id, and the other arguments you're passing to the request (`origin` and/or `offer_id`).
Thanks

**Comment by chancity** [comment] 2018-09-06 14:11
Give me around 10-30 minutes and I'll have it all posted.

**Comment by chancity** [comment] 2018-09-06 14:46
//Test code`            //Test code
            var kinMarketPlaceClient = services.BuildServiceProvider().GetRequiredService<KinMarketPlaceClient>();
            var kinBlockChainHandler = services.BuildServiceProvider().GetRequiredService<KinBlockChainHandler>();
            var kinUserManager = services.BuildServiceProvider().GetRequiredService<KinUserManager>();
            var kinJwtProvider = services.BuildServiceProvider().GetRequiredService<KinJwtProvider>();

            var toUserId = "519ce80f-67e7-44af-ae14-d8e8b475c3ae";
            string fromUserId = Guid.NewGuid().ToString();
            KeyPair keyPair = KeyPair.Random();
            var deviceId = "Kin-Tip-Bot";
            //JWT stuff
            var payload = new KinJwtPayload(KinJwtClaimNames.UserId, fromUserId);
            string jwtToken = kinJwtProvider.GenerateJwtTokenAsync(KinJwtSubjectNames.Register, payload).Result;
            var jwtSignInData = new JwtSignInData(deviceId, keyPair.Address, jwtToken);
            //SignIn
            string requestId = Guid.NewGuid().ToString();
            LoginResponse signInResponse = kinMarketPlaceClient.Users(jwtSignInData, requestId, deviceId).Result;

            if (!string.IsNullOrEmpty(signInResponse.Token))
            {
                //Activate
                requestId = Guid.NewGuid().ToString();

                LoginResponse activationResponse =
                    kinMarketPlaceClient.UsersMeActivate(signInResponse.Token, requestId, deviceId).Result;

                //ChangeTrustOperation
                if (activationResponse.Activated)
                {
                    bool changeTrustResponse = kinBlockChainHandler.TryUntilActivated(keyPair).Result;

                    if (changeTrustResponse)
                    {
                        requestId = Guid.NewGuid().ToString();

                        OffersResponse offers = kinMarketPlaceClient
                            .GetOffers(activationResponse.Token, requestId, deviceId).Result;

                        OfferResponse offerToSubmit =
                            offers.offers.FirstOrDefault(x => x.content_type != "poll" && x.offer_type == "earn");

                        if (offerToSubmit != null)
                        {
                            requestId = Guid.NewGuid().ToString();


                            CreateOrderResponse createOrder = kinMarketPlaceClient.CreateOrderForOffer(offerToSubmit.id,
                                activationResponse.Token,
                                requestId,
                                deviceId).Result;

                            requestId = Guid.NewGuid().ToString();

                            OrderResponse orderResponse = kinMarketPlaceClient
                                .SubmitOrder(createOrder.id, "", activationResponse.Token, requestId, deviceId).Result;
                        }

                        var p2pOffer = new JwtBodyPartOffer($"p2p-tx-test", "1");

                        var sender = new JwtBodyPartSender(fromUserId, "p2p",
                            $"{fromUserId} sending kin to user {toUserId}");

                        var recipient =
                            new JwtBodyPartRecipient(toUserId, "p2p", $"received kin from user {fromUserId}");

                        var offerPayload = new KinJwtPayload<JwtBodyPartOffer>(KinJwtClaimNames.Offer, p2pOffer);
                        var senderPayload = new KinJwtPayload<JwtBodyPartRecipient>(KinJwtClaimNames.Sender, sender);

                        var recipientPayload =
                            new KinJwtPayload<JwtBodyPartRecipient>(KinJwtClaimNames.Recipient, recipient);

                        string jwt = kinJwtProvider.GenerateJwtTokenAsync(KinJwtSubjectNames.PayToUser, offerPayload,
                            senderPayload, recipientPayload).Result;

                        requestId = Guid.NewGuid().ToString();

                        var createOrderResponse = kinMarketPlaceClient
                            .CreateExternalOffer(new JwtRequest(jwt), activationResponse.Token, requestId, deviceId)
                            .Result;

                        //Ops FORGOT TO SEND THIS UHOH
                        //requestId = Guid.NewGuid().ToString();
                        //OrderResponse order = kinMarketPlaceClient.SubmitOrder(createOrderResponse.id, "", activationResponse.Token, requestId, deviceId).Result;


                        try
                        {
                            requestId = Guid.NewGuid().ToString();

                            OrdersResponse orders = kinMarketPlaceClient
                                .GetOrders(activationResponse.Token, requestId, deviceId).Result;
                        }
                        catch (KinApiException e)
                        {
                            Console.WriteLine(JsonConvert.SerializeObject(e.ErrorResponse, Formatting.Indented));
                        }
                    }
                }
            }`

**Comment by chancity** [comment] 2018-09-06 14:51
Use [Fiddler4](https://www.telerik.com/fiddler) to view the http traffic in the error dump.
[error dump.zip](https://github.com/kinecosystem/marketplace-server/files/2357520/error.dump.zip)

Here's the user information: `{"token":"44u1nXD0ClBSAlKXUOwJ","activated":true,"app_id":"rced","user_id":"f2e1472f-5112-4265-a8d4-663948bfc61b","ecosystem_user_id":"UXVPeebOLnJFky7OsYDSs","expiration_date":"2018-09-20T14:44:08.799Z"}`

Here's the json response: `{"code":5002,"error":"Internal Server Error","message":"Opened orders should not be returned"}`

**Comment by chancity** [comment] 2018-09-06 14:56
Error is sourced from[here ](https://github.com/kinecosystem/kin-devplatform-marketplace-server/blob/master/scripts/src/public/services/orders.ts#L369-L372) and is thrown [here ](https://github.com/kinecosystem/kin-devplatform-marketplace-server/blob/master/scripts/src/public/services/orders.ts#L369-L372)in the market place code. 

 From the looks of it this will happen on the developer version and the production version.

**Comment by chancity** [comment] 2018-09-06 14:59
Also I intentionally did this for the error to occur, if I uncomment it everything is fine.

`                        //Ops FORGOT TO SEND THIS UHOH
                        //requestId = Guid.NewGuid().ToString();
                        //OrderResponse order = kinMarketPlaceClient.SubmitOrder(createOrderResponse.id, "", activationResponse.Token, requestId, deviceId).Result;
`

**Comment by nitzantomer** [comment] 2018-09-06 17:26
@chancity 
Ok, we'll take a look at this, thanks.

**Comment by doodyparizada** [comment] 2018-09-08 17:03
@chancity I had a look and I can't reproduce the error. It also never happened on both our production and playground environments. 
Which server endpoint are you using? If you're running locally, which commit hash are you using?

**Comment by chancity** [comment] 2018-09-08 19:06
Mind sending me a snippet of the code you used to test it?

**Comment by chancity** [comment] 2018-09-08 23:49
```
a002e3c0-715e-4d40-8b22-318c745a9f2cfirst order:
{
  "error": null,
  "content": null,
  "status": 0,
  "completion_date": "2018-09-08T23:47:56.716Z",
  "result": null,
  "call_to_action": null,
  "origin": 0,
  "id": "Tke7BMKIyeDGOjfJfyHBc",
  "offer_id": "O6ZalD6T1izSjR9KlIprY",
  "offer_type": "earn",
  "title": "Tutorial",
  "description": "Completed",
  "amount": 130.0,
  "blockchain_data": {
    "transaction_id": "8b0694fc3cdf65708dfacc871f379c402c09ce3291af86b2876c25572149ee3e",
    "sender_address": "GBGF77F3TCY2TVM34YKJNZPXACB5JP4LHNOGK6KUMSNOG2T6NZ6N3ROS",
    "recipient_address": "GCVGVLENJE7S5YEUZIHBRSYMPSJHZH37M52LAZPUQPZOKTXEORFYAK4T"
  }
}
a002e3c0-715e-4d40-8b22-318c745a9f2c Kin Balance: 130
ba059dba-da31-4187-a876-4f0959fded0dfirst order:
{
  "error": null,
  "content": null,
  "status": 0,
  "completion_date": "2018-09-08T23:48:01.873Z",
  "result": null,
  "call_to_action": null,
  "origin": 0,
  "id": "TfFiQHMxwusiaLgs3zFcV",
  "offer_id": "O6ZalD6T1izSjR9KlIprY",
  "offer_type": "earn",
  "title": "Tutorial",
  "description": "Completed",
  "amount": 130.0,
  "blockchain_data": {
    "transaction_id": "41252588d0e4f19cdb8919b565cb984c80430a7809a7f23238c2f6c9c36e94c6",
    "sender_address": "GBGF77F3TCY2TVM34YKJNZPXACB5JP4LHNOGK6KUMSNOG2T6NZ6N3ROS",
    "recipient_address": "GCYKADWQLXJBJCFXY77WBMYJ46FUVZY3Z44YSIWC56H55RFOWVOML3UO"
  }
}
ba059dba-da31-4187-a876-4f0959fded0d Kin Balance: 130
Error: Internal Server Error, Message: Opened orders should not be returned, Code: 5002
a002e3c0-715e-4d40-8b22-318c745a9f2c Kin Balance: 130
Error: Internal Server Error, Message: Opened orders should not be returned, Code: 5002
ba059dba-da31-4187-a876-4f0959fded0d Kin Balance: 130
```

**Comment by chancity** [comment] 2018-09-09 00:08
```

Request ab0ed6e3-518c-4d2a-a05d-5b3895671f4a  url: https://api.developers.kinecosystem.com/v1/users
Request ab0ed6e3-518c-4d2a-a05d-5b3895671f4a  data:
        {"jwt":"eyJhbGciOiJSUzUxMiIsImtpZCI6InJzNTEyXzAiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJyZWdpc3RlciIsImV4cCI6MTUzNjQ3MzI4MSwiaWF0IjoxNTM2NDUxNjgxLCJpc3MiOiJ0ZXN0IiwidXNlcl9pZCI6IjIzNDdjOTBkLTJlMDYtNDE4NC05M2I5LTNkYTg2ZmI0ZWVhZiJ9.lDha38ch4UAgTAfuCArQMRjadVhqhE7kIRVlaSsmBUQ_Jm7fqO9XfJBpDSD_mo5bOjaEQB08j_hfpO2ubwYWU4b1m0LNQSk6V12Ak8bNdoyG1n8Crqto3Cf65RY_A9vwltrnlSGvHiMGhn3zbY7S9A9Bou6zJUYE7Mvl9jaQG_o","device_id":"KinCsharpClient","wallet_address":"GAISMGB35Y43PT72JFYXJTLYGHZKLWWVZRLIJXQTI52YCI6T7X2JB6FW","sign_in_type":"jwt"}

Request fb4f4220-482b-4121-a9d7-9789fc83a2bf  url: https://api.developers.kinecosystem.com/v1/users
Request fb4f4220-482b-4121-a9d7-9789fc83a2bf  data:
        {"jwt":"eyJhbGciOiJSUzUxMiIsImtpZCI6InJzNTEyXzAiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJyZWdpc3RlciIsImV4cCI6MTUzNjQ3MzI4MiwiaWF0IjoxNTM2NDUxNjgyLCJpc3MiOiJ0ZXN0IiwidXNlcl9pZCI6IjM0Y2Y0NTBhLTlhNTctNGU0Ni1hYmUzLTVkNmZjNWEzNzZhOSJ9.Q7O-oAo7o765g0UWYl2v6LxmAtRbuR5w9OT3kZlCZSDlYLOTYfpXGTOBRaSFccqCRuu86236J-7a7X9DajaLphmIecyoJHh8ZwMAgq1R8QmqbnE-RdjImjQeN08dnqOoI3oO7rRZ4OhhxQQ3VRML5_In90kEm2oepnO1UbGGDQA","device_id":"KinCsharpClient","wallet_address":"GBJAWOR7YBWLAM4B3MPQDSHENQM3NPM2BGDYUEUAJIBMZE2OPN64BFLX","sign_in_type":"jwt"}

Response for request fb4f4220-482b-4121-a9d7-9789fc83a2bf  data:
        {"token":"LxmSjwl0zN1z23KgTFJC","activated":false,"app_id":"test","user_id":"34cf450a-9a57-4e46-abe3-5d6fc5a376a9","ecosystem_user_id":"UwVSLylzCdVDh8op8IyIO","expiration_date":"2018-09-23T00:08:00.382Z"}

Response for request ab0ed6e3-518c-4d2a-a05d-5b3895671f4a  data:
        {"token":"kJocDAFEjYbQOgbm5BXP","activated":false,"app_id":"test","user_id":"2347c90d-2e06-4184-93b9-3da86fb4eeaf","ecosystem_user_id":"UGlDWeYofpldbePxvJXbs","expiration_date":"2018-09-23T00:08:00.383Z"}

Request 628c9c01-cfa8-4ecf-ba27-81d45133ddee  url: https://api.developers.kinecosystem.com/v1/users/me/activate

Request ccd6b95e-0b9f-45f1-91c2-4e894880dba4  url: https://api.developers.kinecosystem.com/v1/users/me/activate

Response for request ccd6b95e-0b9f-45f1-91c2-4e894880dba4  data:
        {"token":"jtTNXKiGwQM6dGRlExMF","activated":true,"app_id":"test","user_id":"34cf450a-9a57-4e46-abe3-5d6fc5a376a9","ecosystem_user_id":"UwVSLylzCdVDh8op8IyIO","expiration_date":"2018-09-23T00:08:00.494Z"}

Response for request 628c9c01-cfa8-4ecf-ba27-81d45133ddee  data:
        {"token":"zcNtb44HfcFfuz8QicAW","activated":true,"app_id":"test","user_id":"2347c90d-2e06-4184-93b9-3da86fb4eeaf","ecosystem_user_id":"UGlDWeYofpldbePxvJXbs","expiration_date":"2018-09-23T00:08:00.495Z"}

Request 470ae5cd-ccab-4dd9-a617-e4f288a452d1  url: https://api.developers.kinecosystem.com/v1/orders

Response for request 470ae5cd-ccab-4dd9-a617-e4f288a452d1  data:
        {"orders":[{"id":"T06flAQPfqDGGoXSyPk3G","origin":"marketplace","status":"completed","amount":130,"result":null,"offer_type":"earn","offer_id":"O6ZalD6T1izSjR9KlIprY","title":"Tutorial","error":null,"blockchain_data":{"transaction_id":"32fc748d4a533be935dc03cf720a6c0a096458ce13ccf5c0c12c1afabff770ee","sender_address":"GBGF77F3TCY2TVM34YKJNZPXACB5JP4LHNOGK6KUMSNOG2T6NZ6N3ROS","recipient_address":"GBJAWOR7YBWLAM4B3MPQDSHENQM3NPM2BGDYUEUAJIBMZE2OPN64BFLX"},"completion_date":"2018-09-09T00:08:16.742Z","description":"Completed"}],"paging":{"cursors":{"after":"MTAxNTExOTQ1MjAwNzI5NDE","before":"NDMyNzQyODI3OTQw"},"previous":"https://api.kinmarketplace.com/v1/orders?limit=25&before=NDMyNzQyODI3OTQw","next":"https://api.kinmarketplace.com/v1/orders?limit=25&after=MTAxNTExOTQ1MjAwNzI5NDE="}}

Request 90154d4d-5a07-48b6-bd0d-cdf38d2a0aac  url: https://api.developers.kinecosystem.com/v1/orders

Response for request 90154d4d-5a07-48b6-bd0d-cdf38d2a0aac  data:
        {"orders":[{"id":"TVR5bEpbtG1u9eifGuiRo","origin":"marketplace","status":"completed","amount":130,"result":null,"offer_type":"earn","offer_id":"O6ZalD6T1izSjR9KlIprY","title":"Tutorial","error":null,"blockchain_data":{"transaction_id":"fd153952c96ba3362a707108df4f7890107dd407e5d42b31f392c30d8e67e94a","sender_address":"GBGF77F3TCY2TVM34YKJNZPXACB5JP4LHNOGK6KUMSNOG2T6NZ6N3ROS","recipient_address":"GAISMGB35Y43PT72JFYXJTLYGHZKLWWVZRLIJXQTI52YCI6T7X2JB6FW"},"completion_date":"2018-09-09T00:08:21.855Z","description":"Completed"}],"paging":{"cursors":{"after":"MTAxNTExOTQ1MjAwNzI5NDE","before":"NDMyNzQyODI3OTQw"},"previous":"https://api.kinmarketplace.com/v1/orders?limit=25&before=NDMyNzQyODI3OTQw","next":"https://api.kinmarketplace.com/v1/orders?limit=25&after=MTAxNTExOTQ1MjAwNzI5NDE="}}

Request ff6b4753-333a-4934-bc97-1ea26b1d652d  url: https://api.developers.kinecosystem.com/v1/orders

Response for request ff6b4753-333a-4934-bc97-1ea26b1d652d  data:
        {"code":5002,"error":"Internal Server Error","message":"Opened orders should not be returned"}
Error: Internal Server Error, Message: Opened orders should not be returned, Code: 5002

Request 4d47e821-856f-4705-8dd8-10ea999a2ece  url: https://api.developers.kinecosystem.com/v1/orders

Response for request 4d47e821-856f-4705-8dd8-10ea999a2ece  data:
        {"code":5002,"error":"Internal Server Error","message":"Opened orders should not be returned"}
Error: Internal Server Error, Message: Opened orders should not be returned, Code: 5002

```

**Comment by doodyparizada** [comment] 2018-09-10 13:37
@Ronserruya @mrsegev It's an issue on your branch, can you take it from here?

**Comment by nitzantomer** [comment] 2018-09-13 11:51
Closing this as we weren't able to reproduce it with this repo, maybe it is specific to the developer's fork.

**Closed by nitzantomer** 2018-09-13 11:51 UTC
Labels: bug

**Comment by yosriz** [comment] 2018-09-20 12:12
@chancity please refer to https://github.com/kinecosystem/kin-devplatform-marketplace-server/issues/10
